import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/welcome',
    name: 'Welcome',
    component: () => import('@/views/EntrancePage.vue'),
    meta: { public: true, lightOnly: true },
  },
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/Login.vue'),
    meta: { titleKey: 'routes.login', public: true, lightOnly: true },
  },
  {
    path: '/workspace',
    name: 'ChatWorkspace',
    component: () => import('@/views/workspace/ChatWorkspace.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/users/password',
    name: 'PasswordChange',
    component: () => import('@/views/users/PasswordChangePage.vue'),
    meta: { requiresAuth: true, passwordChangeOnly: true },
  },
  {
    path: '/',
    component: () => import('@/layouts/DefaultLayout.vue'),
    meta: { requiresAuth: true },
    children: [
      {
        path: 'no-access',
        name: 'AccessDenied',
        component: () => import('@/views/AccessDeniedPage.vue'),
        meta: { title: '无访问权限', hidden: true },
      },
      {
        path: '',
        name: 'Dashboard',
        component: () => import('@/views/Dashboard.vue'),
        meta: { titleKey: 'routes.dashboard', icon: 'GridOutline', gateway: 'openclaw' },
      },
      {
        path: 'alerts',
        name: 'AlertNotifications',
        component: () => import('@/views/alerts/AlertNotificationsPage.vue'),
        meta: { title: '告警通知', icon: 'NotificationsOutline', gateway: 'openclaw' },
      },
      {
        path: 'sessions',
        name: 'Sessions',
        component: () => import('@/views/sessions/SessionsPage.vue'),
        meta: {
          titleKey: 'routes.sessions',
          icon: 'ChatbubblesOutline',
          gateway: 'openclaw',
          wideContent: true,
        },
      },
      {
        path: 'sessions/:key',
        name: 'SessionDetail',
        component: () => import('@/views/sessions/SessionDetailPage.vue'),
        meta: { titleKey: 'routes.sessionDetail', hidden: true },
      },
      {
        path: 'memory',
        name: 'Memory',
        component: () => import('@/views/memory/MemoryPage.vue'),
        meta: { titleKey: 'routes.memory', icon: 'BookOutline', gateway: 'openclaw' },
      },
      {
        path: 'cron',
        name: 'Cron',
        component: () => import('@/views/cron/CronPage.vue'),
        meta: { titleKey: 'routes.cron', icon: 'CalendarOutline', gateway: 'openclaw' },
      },
      {
        path: 'models',
        name: 'Models',
        component: () => import('@/views/models/ModelsPage.vue'),
        meta: { titleKey: 'routes.models', icon: 'SparklesOutline', gateway: 'openclaw' },
      },
      {
        path: 'channels',
        name: 'Channels',
        component: () => import('@/views/channels/ChannelsPage.vue'),
        meta: { titleKey: 'routes.channels', icon: 'GitNetworkOutline', gateway: 'openclaw' },
      },
      {
        path: 'skills',
        name: 'Skills',
        component: () => import('@/views/skills/SkillsPage.vue'),
        meta: { titleKey: 'routes.skills', icon: 'ExtensionPuzzleOutline', gateway: 'openclaw' },
      },
      {
        path: 'system',
        name: 'System',
        component: () => import('@/views/system/SystemPage.vue'),
        meta: { titleKey: 'routes.system', icon: 'PulseOutline', gateway: 'openclaw' },
      },
      {
        path: 'files',
        name: 'Files',
        component: () => import('@/views/files/FilesPage.vue'),
        meta: { title: '报告文件管理', icon: 'FolderOutline', gateway: 'openclaw' },
      },
      {
        path: 'agents',
        name: 'Agents',
        component: () => import('@/views/agents/AgentsPage.vue'),
        meta: { titleKey: 'routes.agents', icon: 'PeopleOutline', gateway: 'openclaw' },
      },
      {
        path: 'office',
        name: 'Office',
        component: () => import('@/views/office/OfficePage.vue'),
        meta: { titleKey: 'routes.office', icon: 'ConstructOutline', gateway: 'openclaw' },
      },
      {
        path: 'users',
        name: 'UserManagement',
        component: () => import('@/views/users/UserManagementPage.vue'),
        meta: { titleKey: 'routes.userManagement', icon: 'PeopleOutline', gateway: 'openclaw' },
      },
      {
        path: 'users/create',
        name: 'UserCreate',
        component: () => import('@/views/users/UserCreatePage.vue'),
        meta: { hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'users/:id/edit',
        name: 'UserEdit',
        component: () => import('@/views/users/UserEditPage.vue'),
        meta: { hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'audit-logs',
        name: 'AuditLogs',
        component: () => import('@/views/audit/AuditLogsPage.vue'),
        meta: { title: '审计信息', icon: 'DocumentTextOutline', gateway: 'openclaw' },
      },
      {
        path: 'settings',
        name: 'Settings',
        component: () => import('@/views/settings/SettingsPage.vue'),
        meta: { titleKey: 'routes.settings', icon: 'CogOutline', gateway: 'openclaw' },
      },
        {
          path: 'system-configuration',
          name: 'SystemConfiguration',
          component: () => import('@/views/settings/SystemConfigurationPage.vue'),
          meta: { title: '系统配置', icon: 'SettingsOutline', gateway: 'openclaw' },
        },
      {
        path: 'system-configuration/gaiop-service',
          name: 'GAIOPServiceConfiguration',
          component: () => import('@/views/settings/GAIOPServiceConfigurationPage.vue'),
          meta: { hidden: true, gateway: 'openclaw' },
        },
      {
        path: 'system-configuration/data-sources',
        name: 'DataSourceManagement',
        component: () => import('@/views/settings/DataSourceManagementPage.vue'),
        meta: { hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'system-configuration/alert-ingestion',
        name: 'AlertIngestionConfiguration',
        component: () => import('@/views/settings/AlertIngestionConfigurationPage.vue'),
        meta: { hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'system-configuration/data-sources/create',
        name: 'DataSourceCreate',
        component: () => import('@/views/settings/DataSourceFormPage.vue'),
        meta: { hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'system-configuration/data-sources/:id/edit',
        name: 'DataSourceEdit',
        component: () => import('@/views/settings/DataSourceFormPage.vue'),
        meta: { hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'system-configuration/environment',
        name: 'EnvironmentManagement',
        component: () => import('@/views/settings/SensitiveConfigPage.vue'),
        meta: { hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'system-configuration/alert-forwarding',
        name: 'AlertForwardingConfiguration',
        component: () => import('@/views/settings/ConfigurationPlaceholderPage.vue'),
        props: { module: 'alert' },
        meta: { hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'system-upgrade',
        name: 'SystemUpgrade',
        component: () => import('@/views/settings/SystemUpgradePage.vue'),
        meta: { titleKey: 'routes.systemUpgrade', icon: 'ArchiveOutline', gateway: 'openclaw' },
      },
      {
        path: 'settings/basic',
        name: 'BasicSettings',
        redirect: { name: 'Settings' },
        meta: { hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'settings/session-management',
        name: 'SessionManagement',
        component: () => import('@/views/settings/SessionManagementPage.vue'),
        meta: { title: '会话时长管理', hidden: true, gateway: 'openclaw' },
      },
      {
        path: 'settings/report-storage',
        name: 'ReportStorage',
        redirect: { name: 'Settings' },
        meta: { title: '报告存储位置', hidden: true, gateway: 'openclaw' },
      },
    ],
  },
  {
    path: '/:pathMatch(.*)*',
    redirect: { name: 'Dashboard' },
  },
]
